#! /bin/sh
/bin/mount -a
/bin/mount -t tmpfs mdev /dev
/bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
/bin/chmod 777 /mnt
/sbin/ifconfig eth2 192.168.1.55
/usr/bin/rpcbind
/usr/sbin/rpc.nfsd
/usr/sbin/rpc.mountd
/usr/sbin/mdadm --assemble /dev/md0 /dev/sda1 /dev/sdb1
/bin/mount -t ext2 /dev/md0 /mnt
/bin/chmod 777 /mnt
/usr/sbin/exportfs -av
/sbin/insmod /lib/modules/3.6.11/kernel/i2c/i2c_ltc2991.ko
/sbin/insmod /lib/modules/3.6.11/kernel/i2c/rwtemp_v.ko
/sbin/insmod /lib/modules/3.6.11/kernel/fpga/fpga.ko
/bin/mknod /dev/fpga c 249 0
/bin/mknod /dev/read_sensor c 244 0
/usr/bin/ibmc.bin
